apiVersion: v1
kind: Service
metadata:
  name: ping #name of the sservice
spec:
  type: LoadBalancer
  selector:
    app: ping #which pods qualify for forwarding ]
  ports:
  - port: 80 #port on service external
    targetPort: 9696 # port on the pod 
